// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBiPOBsMAoSiLwjdPW_5hjUTPW49CX3pnA',
    appId: '1:1098068850332:web:eb492af6efcd5a39ad1f59',
    messagingSenderId: '1098068850332',
    projectId: 'chambas-c56a2',
    authDomain: 'chambas-c56a2.firebaseapp.com',
    storageBucket: 'chambas-c56a2.firebasestorage.app',
    measurementId: 'G-Z5TFH75PNY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD1GkFL6POkF5WCSEZiZoR8QCEGRfiwpIM',
    appId: '1:1098068850332:android:e3be87324cc0a872ad1f59',
    messagingSenderId: '1098068850332',
    projectId: 'chambas-c56a2',
    storageBucket: 'chambas-c56a2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBoer5iwVrn6KwhbpAwdIRcoXOi3GLGTRs',
    appId: '1:1098068850332:ios:c78c6344c1fcb667ad1f59',
    messagingSenderId: '1098068850332',
    projectId: 'chambas-c56a2',
    storageBucket: 'chambas-c56a2.firebasestorage.app',
    iosBundleId: 'com.example.chambas',
  );
}
